services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  db_service:
    build:
      context: ./db_service
    container_name: db_service
    ports:
      - "8000:8000"
    volumes:
      - ./db_service:/app

  auth_service:
    build:
      context: ./auth_service
    container_name: auth_service
    ports:
      - "8001:8001"
    volumes:
      - ./auth_service:/app

  game_service:
    build:
      context: ./game_service
    container_name: game_service
    ports:
      - "8002:8002"
    depends_on:
      - db_service
    volumes:
      - ./game_service:/app

  finance_service:
    build:
      context: ./finance_service
    container_name: finance_service
    ports:
      - "8003:8003"
    depends_on:
      - db_service
    volumes:
      - ./finance_service:/app

  report_service:
    build:
      context: ./report_service
    container_name: report_service
    ports:
      - "8004:8004"
    depends_on:
      - db_service
    volumes:
      - ./report_service:/app

  notification_service:
    build:
      context: ./notification_service
    container_name: notification_service
    depends_on:
      - rabbitmq
    volumes:
      - ./notification_service:/app
